#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

FIREBASE_PROJECT="progress-board-d03d1"
GH_REPO="JockeGrege/project-dashboard"
PAGES_DOMAIN="jockegrege.github.io"
PAGES_URL="https://jockegrege.github.io/project-dashboard/"
CONFIG_KEYS=(
  VITE_FIREBASE_API_KEY
  VITE_FIREBASE_AUTH_DOMAIN
  VITE_FIREBASE_PROJECT_ID
  VITE_FIREBASE_STORAGE_BUCKET
  VITE_FIREBASE_MESSAGING_SENDER_ID
  VITE_FIREBASE_APP_ID
)

banner "Take Project Improvement Tracker live on Firebase + GitHub Pages"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Prerequisites"
say "Checking the tools this wizard drives."

if [[ ! -f "$ENV_FILE" ]]; then
  warn "No $ENV_FILE found. Run:  cp .env.example .env   then re-run this script."
  exit 1
fi

# firebase CLI + project access
if ! command -v firebase >/dev/null 2>&1; then
  warn "firebase CLI not found. Install:  npm i -g firebase-tools   then re-run."
  exit 1
fi
if ! firebase projects:list 2>/dev/null | grep -q "$FIREBASE_PROJECT"; then
  warn "The logged-in firebase account can't see project '$FIREBASE_PROJECT'."
  step "Run:  firebase login   (use the Google account with access to that project)"
  pause "Done? Press Enter to re-check."
  firebase projects:list 2>/dev/null | grep -q "$FIREBASE_PROJECT" \
    || { warn "Still can't see it. Sort out firebase access, then re-run."; exit 1; }
fi
say "${GREEN}✓${RESET} firebase CLI sees $FIREBASE_PROJECT"

# Firestore database exists
if ! firebase firestore:databases:get "(default)" --project "$FIREBASE_PROJECT" >/dev/null 2>&1; then
  warn "No Firestore database in $FIREBASE_PROJECT yet."
  open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT/firestore"
  step "Create database → Production mode → pick the region nearest you → Enable."
  pause "Created? Press Enter to re-check."
  firebase firestore:databases:get "(default)" --project "$FIREBASE_PROJECT" >/dev/null 2>&1 \
    || { warn "Still no database. Create it, then re-run."; exit 1; }
fi
say "${GREEN}✓${RESET} Firestore database exists"

# gh CLI authenticated (secrets need this)
while ! { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }; do
  if ! command -v gh >/dev/null 2>&1; then
    warn "GitHub CLI not found. Install it (https://cli.github.com), then continue."
  else
    warn "GitHub CLI isn't authenticated."
    step "In another terminal run:  gh auth login -h github.com"
  fi
  pause "Done? Press Enter to re-check."
done
gh repo set-default "$GH_REPO" >/dev/null 2>&1 || true
say "${GREEN}✓${RESET} gh authenticated"

# on main, and it tracks origin
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  warn "You're on '$CURRENT_BRANCH', not main. The deploy stage pushes main."
  confirm "Switch to main now?" && git checkout main
fi
say "${GREEN}✓${RESET} prerequisites OK"
pause "Press Enter to continue."

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Confirm the owner account (VITE_ALLOWED_UID)"
say "This is the ONE Google account allowed to read or write your board."
CURRENT_UID=$(_existing VITE_ALLOWED_UID || true)
if [[ -n "$CURRENT_UID" && "$CURRENT_UID" != "__REPLACE_ME__" ]]; then
  say "Current: ${BOLD}${CURRENT_UID}${RESET}"
  if confirm "Keep this UID?"; then
    VITE_ALLOWED_UID="$CURRENT_UID"
  fi
fi
if [[ -z "${VITE_ALLOWED_UID:-}" || "${VITE_ALLOWED_UID}" == "__REPLACE_ME__" ]]; then
  say "To get your UID: point the local app at live Firebase and sign in once."
  step "In another terminal:  VITE_FIREBASE_TARGET=live npm run dev"
  open_url "http://localhost:5173/project-dashboard/"
  step "Click 'Continue with Google', choose the account you want as sole owner."
  step "A banner shows your UID with a copy button. Copy it, then stop that dev server."
  ask VITE_ALLOWED_UID "Paste your UID:"
fi
[[ -n "${VITE_ALLOWED_UID:-}" && "${VITE_ALLOWED_UID}" != "__REPLACE_ME__" ]] \
  || { warn "No UID captured. Re-run when you have it."; exit 1; }
write_env VITE_ALLOWED_UID "$VITE_ALLOWED_UID"
pause "Press Enter to continue."

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "GitHub Actions secrets"
say "The deploy workflow builds with these. Setting them from $ENV_FILE."
for key in "${CONFIG_KEYS[@]}"; do
  val=$(_existing "$key" || true)
  if [[ -z "$val" ]]; then
    warn "$key missing from $ENV_FILE — copy it from .env.example, then re-run."
    exit 1
  fi
  set_secret "$key" "$val"
done
set_secret VITE_ALLOWED_UID "$VITE_ALLOWED_UID"
note "VITE_FIREBASE_TARGET is set to 'live' directly in the workflow, not a secret."
pause "Press Enter to continue."

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Deploy the Firestore security rules"
say "Generates firestore.rules from the template (pinned to your UID) and deploys."
say "After this, ONLY ${BOLD}${VITE_ALLOWED_UID}${RESET} can read or write the database."
if confirm "Deploy the rules now?"; then
  if npm run deploy:rules; then
    say "${GREEN}✓${RESET} rules deployed"
  else
    warn "Rule deploy failed. Fix the error above, then run:  npm run deploy:rules"
    SKIPPED+=("firestore rules deploy (npm run deploy:rules)")
  fi
else
  SKIPPED+=("firestore rules deploy (npm run deploy:rules)")
fi
pause "Press Enter to continue."

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Authorise the Pages domain for Google sign-in"
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT/authentication/settings"
step "Under 'Authorized domains', click 'Add domain'."
step "Enter:  ${BOLD}${PAGES_DOMAIN}${RESET}   then click Add."
note "Without this, Google sign-in is rejected on the deployed site."
pause "Added? Press Enter to continue."

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Enable GitHub Pages"
open_url "https://github.com/$GH_REPO/settings/pages"
step "Under 'Build and deployment' → 'Source', choose ${BOLD}GitHub Actions${RESET}."
note "No branch to pick — the deploy workflow publishes the built site."
pause "Set? Press Enter to continue."

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Deploy"
say "The workflow runs: lint → unit tests → e2e → build → publish to Pages."
say "An earlier run may have failed because the secrets weren't set yet — that's"
say "expected. This re-triggers it now that they are."
git fetch origin main --quiet 2>/dev/null || true

if [[ -n "$(git status --porcelain)" ]]; then
  say "Uncommitted changes in the working tree:"
  git status --short | sed 's/^/    /'
  if confirm "Commit and push them?"; then
    git add -A
    git commit -m "Wire go-live config"
    git push origin main
  fi
fi

# Everything already on origin/main? Trigger the workflow directly.
if [[ -z "$(git log --oneline origin/main..HEAD 2>/dev/null)" ]]; then
  if confirm "Trigger the deploy workflow on main now?"; then
    gh workflow run deploy.yml --ref main \
      && say "${GREEN}✓${RESET} deploy started" \
      || SKIPPED+=("trigger deploy (gh workflow run deploy.yml --ref main)")
  else
    SKIPPED+=("trigger deploy (gh workflow run deploy.yml --ref main)")
  fi
elif confirm "Push main and start the deploy?"; then
  git push origin main
else
  SKIPPED+=("git push origin main  (starts the deploy)")
fi

open_url "https://github.com/$GH_REPO/actions"
say "Watch the run there. When it's green the site is live at:"
say "  ${BOLD}${PAGES_URL}${RESET}"

finish
say "Live URL once the Action passes:  ${BOLD}${PAGES_URL}${RESET}"
note "Re-run this script any time — it keeps values already saved."
