#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Run from the repo root so ENV_FILE resolves to ./.env and ./worker exists.
cd "$(dirname "$0")/.."

if [[ ! -d worker ]]; then
  warn "can't find the worker/ directory next to this script — run it from the repo."
  exit 1
fi

banner "Hypomone image-upload setup"

say "This connects the 'paste a screenshot into an issue' feature:"
note "  browser → your Cloudflare Worker → imgbb → just the URL is stored"
note "The imgbb API key lives only as a Worker secret — never in the app."
say ""
say "Before you start, have these ready (all free, sign-up links open as needed):"
step "An imgbb account            — https://imgbb.com/signup"
step "A Cloudflare account        — sign-up is on the 'wrangler login' page"
step "Optional: the GitHub CLI ('gh', logged in) so stage 5 can set the"
note "         VITE_IMAGE_UPLOAD_URL Actions secret for you. Without it the"
note "         script prints the one command to run by hand later — it only"
note "         affects the DEPLOYED site, not local dev."
say ""
note "This is idempotent: stop any time with Ctrl-C and re-run."
pause "Press Enter to begin."

# ── Stage 1: imgbb API key ──────────────────────────────────────────────
stage "imgbb: get an API key"
say "You need an imgbb API key. It authorises uploads to your imgbb account."
step "If you're not signed in to imgbb, sign in (or create a free account)."
open_url "https://imgbb.com/signup"
step "Then open the API page (opening now):"
open_url "https://api.imgbb.com/"
step "Click 'Get API key' / 'Add' and copy the key it shows."
ask_secret IMGBB_API_KEY "Paste the imgbb API key:"
if [[ -z "${IMGBB_API_KEY:-}" ]]; then
  warn "no API key entered — re-run when you have it."
  exit 1
fi
note "Held in memory for stage 3. It is not written to $ENV_FILE."

# ── Stage 2: Cloudflare — install & sign in ─────────────────────────────
stage "Cloudflare: install tooling and sign in"
say "Wrangler is Cloudflare's CLI. It deploys the Worker in worker/."
step "Installing the Worker's dependencies (npm install in worker/)…"
( cd worker && npm install )
step "A browser tab will open to authorise Wrangler with your Cloudflare account."
note "No Cloudflare account yet? The sign-in page has a free sign-up."
pause "Press Enter to run 'wrangler login'."
( cd worker && npx wrangler login )
confirm "Did Wrangler report you're logged in?" || {
  warn "Sign-in didn't complete. Re-run this wizard once 'npx wrangler whoami' works."
  exit 1
}

# ── Stage 3: store the imgbb API key as a Worker secret ─────────────────
stage "Cloudflare: store the imgbb API key as a secret"
say "This uploads IMGBB_API_KEY to Cloudflare, encrypted. It never touches git."
step "Sending it to 'wrangler secret put IMGBB_API_KEY'…"
printf '%s\n' "$IMGBB_API_KEY" | ( cd worker && npx wrangler secret put IMGBB_API_KEY )
note "If that failed, run it yourself: cd worker && npx wrangler secret put IMGBB_API_KEY"

# ── Stage 4: deploy the Worker ─────────────────────────────────────────
stage "Cloudflare: deploy the Worker"
say "This publishes worker/src/index.ts and prints its public URL."
pause "Press Enter to run 'wrangler deploy'."
( cd worker && npx wrangler deploy )
say ""
step "In the output above, find the line like:"
note "    https://hypomone-image-upload.<your-subdomain>.workers.dev"
while : ; do
  ask VITE_IMAGE_UPLOAD_URL "Paste that full https:// URL:"
  case "${VITE_IMAGE_UPLOAD_URL:-}" in
    https://*) break ;;
    http://*)
      # http:// 301s to https:// on Cloudflare and breaks the browser's CORS
      # fetch — take the https form only.
      VITE_IMAGE_UPLOAD_URL="https://${VITE_IMAGE_UPLOAD_URL#http://}"
      say "  → using ${VITE_IMAGE_UPLOAD_URL} (https)"
      break ;;
    *) warn "must start with https:// — copy the workers.dev line from above." ;;
  esac
done

# ── Stage 5: wire the app to the Worker ───────────────────────────────
stage "App: point Hypomone at the Worker"
say "Local dev reads $ENV_FILE; the deployed site reads a GitHub Actions secret."
write_env VITE_IMAGE_UPLOAD_URL "$VITE_IMAGE_UPLOAD_URL"
set_secret VITE_IMAGE_UPLOAD_URL "$VITE_IMAGE_UPLOAD_URL"
note "The GitHub secret is read by .github/workflows/deploy.yml on the next deploy."

# ── Stage 6: verify ──────────────────────────────────────────────────
stage "Verify"
say "Try it end to end:"
step "RESTART the dev server ('npm run dev') — it only reads .env at startup,"
note "     so a server left running from before won't have VITE_IMAGE_UPLOAD_URL."
step "Open a project, click into 'Add an issue…', paste a screenshot (Cmd/Ctrl+V)."
step "The thumbnail should upload, then load the real imgbb image once filed."
step "Watch the Worker's logs in another terminal:  cd worker && npx wrangler tail"
note "Only the imgbb URL is saved with the issue; the image bytes never hit Firebase."
say ""
say "From here on:"
note "  • Local dev works now (with the dev server restarted)."
note "  • The deployed site picks this up only after the VITE_IMAGE_UPLOAD_URL"
note "    Actions secret is set AND this branch is merged to main."
note "  • Change the allowed browser origins in worker/wrangler.toml, then"
note "    re-deploy:  cd worker && npx wrangler deploy"
note "  • Re-run this script any time to change the imgbb key or the URL."
pause "Press Enter when you've confirmed it works (or to finish anyway)."

finish
